services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: crypto-signal-vpn

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

    volumes:
      - ./gluetun:/gluetun:ro

    environment:
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      TZ: Asia/Jakarta

    ports:
      - "${PORT:-11000}:${PORT:-11000}"

    restart: unless-stopped

  app:
    build: .
    container_name: crypto-signal

    network_mode: "service:vpn"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      vpn:
        condition: service_healthy

    restart: unless-stopped
